apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: funny-facts-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Breakingbread/argo-cd-templates
    targetRevision: HEAD
    path: facts-microservice
    helm:
      valueFiles:
        - values-funny.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
