replicaCount: 1

image:
  repository: 'ghcr.io/breakingbread/facts-microservice'
containerPort: 8080

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

appLabel: funny-application

requestUrl: 'https://api.chucknorris.io/jokes/random'

rules:
  domain: funnyfact.local
  path: /funnyfact


