replicaCount: 1

image:
  repository: 'ghcr.io/breakingbread/facts-microservice'
containerPort: 8080

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

appLabel: useless-application

requestUrl: 'uselessfacts.jsph.pl/api/v2/facts/random'

rules:
  domain: useless.local
  path: /uselessfact
