apiVersion: v1
kind: Pod
metadata:
  name: curlpod
  labels:
    purpose: demonstrate-curl
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["/bin/sh", "-c", "while true; do sleep 30; done"]