apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabel }}-deployment
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: facts-microservice
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
          - name: REQUEST_URL
            value: {{ .Values.requestUrl }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabel }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}