name: Triggered Workflow

on:
  repository_dispatch:
    types: [patch_version]

jobs:
  update-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parse payload
        run: |
          echo "version=${{ github.event.client_payload.version }}" >> "$GITHUB_ENV"
          echo "Application Version: $version"

      - name: Patch helm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "s/appVersion:.*/appVersion: $version/" facts-microservice/Chart.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add facts-microservice/Chart.yaml
          git commit -m "Update appVersion to $version"
          git push
        
          
